version: '2'
services:
  web:
    build: .
    links:
      - db:db
    ports:
      - 8004:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - ./config:/docker-entrypoint-initdb.d
